### ISSUE TITLE
Are the datasets publickly available?

### ISSUE THREAD

**Issue by coffezhou** [OpenDFM/ChemDFM#1]
ChemDFM is an excellent work, which is trained on many datasets. The preprocessing of these datasets is very time consuming. So could you please make these datasets publickly available?

**Comment by TravelLeraLone** [comment]
Thank you for your interest in ChemDFM! We will open-source part of our instruction-tuning dataset in the near future. I hope this answers your question. If you have any other questions or needs, please feel free to contact us.
